### ISSUE TITLE
A humble feature request: Insertion of extra points

### ISSUE THREAD

**Issue by kristoffer-dyrkorn** [kylebarron/pydelatin#31]
Thank you for an excellent library!

I have a use case where I would like to add elevation points at specific locations. For example, after having run the simplifier, I would like to insert some extra points (that I select) from the heightmap into the triangulation to have maximum accuracy (ie full resolution) there.

I have had a look at the code (src/triangulator.cpp) but cannot quite find out how to proceed. It seems the triangulation process (in Triangulator::Step()) is triangle-driven, ie it starts with a candidate triangle (the one having the maximum vertical error to a vertex), finds the candidate point for that triangle, inserts it and re-triangulates.

Do you know of a way to start with a point instead? I have thought of somehow marking the triangle containing each extra points with a very high dummy error value, and then proceed from there, but it seems I would then need to find the enclosing triangles for all of those extra points. Is there a simpler way? 

It might be sufficient for my use case to use a bounding box to define the extra points, and then the error calculation / candidate finding process could perhaps be overridden with an extra criterion, for example: If a given point is inside that bounding box, then don't calculate the vertex-to-plane distance, instead just set it to some max value - and/or add the point directly to the candidate queue. Do you see other options?

With a little bit of input on how to approach this I could likely implement the solution myself and post it here as a PR.

**Comment by kylebarron** [comment]
I haven't looked at this code in a while. It might make more sense to ask on [hmm](https://github.com/fogleman/hmm) but my guess is that inserting extra points is not trivial

**Comment by kristoffer-dyrkorn** [comment]
Ok! Thanks for your suggestion!
