### ISSUE TITLE
cant generate 3d mesh file from delatin web

### ISSUE THREAD

**Issue by sugizo** [kylebarron/pydelatin#35]
**source png downloaded from https://mapbox.github.io/delatin (bay area, usa saved after height counted stop)**
![bay_area_usa](https://github.com/kylebarron/pydelatin/assets/2418295/844cb594-7908-442c-ab31-5aafa7949459)

**code**
```
import imageio.v2 as imageio
import meshio
from pydelatin import Delatin
from pydelatin.util import decode_ele, rescale_positions

path = './bay_area_usa.png'
img= imageio.imread(path)
terrain = decode_ele(img, 'mapbox')
tin = Delatin(terrain, max_error = 30)
vertices, triangles = tin.vertices, tin.triangles
cells = [("triangle", triangles) ]
mesh = meshio.Mesh(vertices, cells)
mesh.write('bay_area_usa.stl')
```

**result not expected**
![image](https://github.com/kylebarron/pydelatin/assets/2418295/0624891f-1607-4a8d-8d34-359a91bc95dd)

**expected result**
can see the terrain elevation in 3d format (*.stl)

**n.b.**
- saved file size is 1280 x 1280 got same result
- resized the source file into 512 x 512 got same result
- tried every images provide from delatin web, got same result

best regards

**Comment by kylebarron** [comment]
> **source png downloaded from https://mapbox.github.io/delatin (bay area, usa saved after height counted stop)**

That's the visual representation of the mesh from the **output** of delatin. It's not the input.

If you look at the network tab, you can copy the `curl` command to fetch it
```
curl 'https://a.tiles.mapbox.com/v4/mapbox.terrain-rgb/11/2014/1267@2x.png?access_token=pk.eyJ1IjoibW91cm5lciIsImEiOiJjbG83ZDF0ZGgwNTJ1MmtsajF1ZDN0c3ZvIn0.56k4reJ2cZAGNVklIGCXnQ' \
  -H 'sec-ch-ua: "Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"' \
  -H 'Referer: https://mapbox.github.io/' \
  -H 'Origin: https://mapbox.github.io' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua-platform: "macOS"' > terrain.png
```

This is the input data meant to be passed to the algorithm
![terrain](https://github.com/kylebarron/pydelatin/assets/15164633/73c66a2c-8d8a-426c-9897-bbc0abc56dbd)
